#!/usr/bin/env node
/**
 * Generates the es5-conformance acceptance suite from a pinned Test262 checkout.
 *
 * Boundary A of the Test262 axis: the ES5, in-scope, sloppy tests under
 * `language/expressions` for the arithmetic (`+ - * / %`), relational
 * (`< <= > >=`) and equality (`== != === !==`) operators. Each Test262 test is
 * self-checking — it runs a small assertion library (`sta.js` + `assert.js`)
 * plus a body that throws on a wrong result — so there is no external oracle:
 * a case passes iff the assembled program runs without an escaping exception
 * (and prints the liveness sentinel; see test262.ts).
 *
 *   TEST262_DIR=/path/to/test262 node bench/es5-conformance/generate.ts
 *   TEST262_DIR=/path/to/test262 node bench/es5-conformance/generate.ts --check
 *
 * Regeneration needs a Test262 checkout at pin PIN below; running the benchmark
 * needs only the committed `acceptance/` (the bodies travel inlined). The vet,
 * emit and write mechanics are shared with the other Test262-axis jobs via
 * suite.ts; this file is the boundary-A config.
 */
import * as acorn from "acorn";
import path from "node:path";
import { CHAPTERS_A, type Case } from "./test262.ts";
import { collectCases, harnessOf } from "./corpus.ts";
import { emitHarnessModule, emitTestFile, finalize, packFiles, vetCase } from "./suite.ts";
import { requireCheckoutAtPin } from "./checkout.ts";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const OUT = path.join(HERE, "acceptance");
const PACKAGE = "es5-conformance";
const PIN = "3655e7464de3d52643ecddd4b5f9f4f3e7f62398";
const READ_LIMIT = 80_000;
const CAP = 68_000; // per test-file inlined budget, with headroom under READ_LIMIT
const ACORN_VERSION: string = (acorn as unknown as { version: string }).version;

const HEADER = `// Generated by generate.ts from Test262 @ ${PIN.slice(0, 8)} (harness ${"sta.js+assert.js"}); do not edit by hand.\n`;

function main(argv: string[]): number {
  const dir = requireCheckoutAtPin(PIN);
  const harness = harnessOf(dir);
  const cases = collectCases(dir, CHAPTERS_A);
  const problems = cases.flatMap((c) => vetCase(c, harness));
  if (problems.length) throw new Error(`case problems (${problems.length}):\n  ${problems.slice(0, 40).join("\n  ")}`);

  const byChapter = new Map<string, Case[]>();
  for (const c of cases) (byChapter.get(c.chapter) ?? byChapter.set(c.chapter, []).get(c.chapter)!).push(c);
  const files: Record<string, string> = { "support/harness.ts": emitHarnessModule(HEADER, harness) };
  for (const chapter of CHAPTERS_A) {
    const cs = byChapter.get(chapter);
    if (!cs || !cs.length) continue;
    const render = (group: Case[]) => emitTestFile(HEADER, PACKAGE, "language/expressions/" + chapter, group);
    for (const [name, content] of packFiles(chapter, cs, render, CAP)) files[name] = content;
  }

  return finalize(files, cases.length, {
    out: OUT,
    readLimit: READ_LIMIT,
    check: argv.includes("--check"),
    footer: `vetted with node vm + acorn ${ACORN_VERSION} against Test262 @ ${PIN.slice(0, 8)}`,
  });
}

process.exit(main(process.argv.slice(2)));
