#!/usr/bin/env node
/**
 * Generates the es5-language acceptance suite from a pinned Test262 checkout.
 *
 * Boundary D of the Test262 axis: every ES5, in-scope, sloppy test under
 * `test/language` — expressions, statements, ASI, scope, types, literals,
 * identifiers, white space, comments, `arguments` — collected recursively.
 * Unlike boundary A this includes **negative** cases (mostly parse-phase
 * `SyntaxError`); the verdict logic is unchanged (`test262.judge`).
 *
 *   TEST262_DIR=/path/to/test262 node bench/es5-language/generate.ts
 *   TEST262_DIR=/path/to/test262 node bench/es5-language/generate.ts --check
 *
 * All mechanics — scope rules, vetting against Node vm + acorn, emission,
 * byte-reproducible `--check` — are shared with the other Test262-axis jobs
 * via ../es5-conformance/{test262,corpus,suite,checkout}.ts (unit-tested
 * there). This file is only the boundary-D config: the tree root, the
 * grouping of emitted files, and the package name.
 */
import path from "node:path";
import { ACORN_VERSION, type Case } from "../es5-conformance/test262.ts";
import { collectTree, harnessOf } from "../es5-conformance/corpus.ts";
import { emitHarnessModule, emitTestFile, finalize, packFiles, vetCase } from "../es5-conformance/suite.ts";
import { requireCheckoutAtPin } from "../es5-conformance/checkout.ts";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const OUT = path.join(HERE, "acceptance");
const PACKAGE = "es5-language";
const ROOT = "language";
const PIN = "3655e7464de3d52643ecddd4b5f9f4f3e7f62398";
const READ_LIMIT = 80_000;
const CAP = 68_000; // per test-file inlined budget, with headroom under READ_LIMIT

const HEADER = `// Generated by generate.ts from Test262 @ ${PIN.slice(0, 8)} (harness ${"sta.js+assert.js"}); do not edit by hand.\n`;

// Emitted files are grouped by the segment under `language/` (expressions,
// statements, literals, …), bin-packed under CAP as `<segment>-N.test.ts`.
function groupOf(c: Case): string {
  return c.chapter.split("/")[1] ?? "misc";
}

function main(argv: string[]): number {
  const dir = requireCheckoutAtPin(PIN);
  const harness = harnessOf(dir);
  const cases = collectTree(dir, ROOT);
  const problems = cases.flatMap((c) => vetCase(c, harness));
  if (problems.length) throw new Error(`case problems (${problems.length}):\n  ${problems.slice(0, 60).join("\n  ")}`);

  const byGroup = new Map<string, Case[]>();
  for (const c of cases) (byGroup.get(groupOf(c)) ?? byGroup.set(groupOf(c), []).get(groupOf(c))!).push(c);
  const files: Record<string, string> = { "support/harness.ts": emitHarnessModule(HEADER, harness) };
  for (const group of [...byGroup.keys()].sort()) {
    const cs = byGroup.get(group)!;
    const render = (chunk: Case[]) => emitTestFile(HEADER, PACKAGE, `${ROOT}/${group}`, chunk);
    for (const [name, content] of packFiles(group, cs, render, CAP)) files[name] = content;
  }

  const negatives = cases.filter((c) => c.expected !== null).length;
  console.log(`${cases.length} cases (${cases.length - negatives} positive, ${negatives} negative) across ${byGroup.size} groups`);
  return finalize(files, cases.length, {
    out: OUT,
    readLimit: READ_LIMIT,
    check: argv.includes("--check"),
    footer: `vetted with node vm + acorn ${ACORN_VERSION} against Test262 @ ${PIN.slice(0, 8)}`,
  });
}

process.exit(main(process.argv.slice(2)));
