import type { Value, Vec } from './core.js';
export declare const of: <T extends Value>(...xs: readonly T[]) => Vec<T>;
export declare const from: <T extends Value>(xs: Iterable<T>) => Vec<T>;
export declare const empty: <T extends Value>() => Vec<T>;
export declare const count: (v: Vec<Value>) => number;
export declare const isEmpty: (v: Vec<Value>) => boolean;
export declare const nth: <T extends Value>(v: Vec<T>, i: number) => T | undefined;
export declare const first: <T extends Value>(v: Vec<T>) => T | undefined;
export declare const last: <T extends Value>(v: Vec<T>) => T | undefined;
export declare const push: <T extends Value>(v: Vec<T>, x: T) => Vec<T>;
export declare const pop: <T extends Value>(v: Vec<T>) => Vec<T>;
export declare const setNth: <T extends Value>(v: Vec<T>, i: number, x: T) => Vec<T>;
export declare const updateNth: <T extends Value>(v: Vec<T>, i: number, f: (x: T) => T) => Vec<T>;
export declare const slice: <T extends Value>(v: Vec<T>, start?: number, end?: number) => Vec<T>;
export declare const concat: <T extends Value>(a: Vec<T>, b: Vec<T>) => Vec<T>;
export declare const reverse: <T extends Value>(v: Vec<T>) => Vec<T>;
export declare const map: <T extends Value, U extends Value>(v: Vec<T>, f: (x: T, i: number) => U) => Vec<U>;
export declare const filter: <T extends Value>(v: Vec<T>, p: (x: T, i: number) => boolean) => Vec<T>;
export declare const reduce: <T extends Value, A>(v: Vec<T>, init: A, f: (acc: A, x: T, i: number) => A) => A;
export declare const some: <T extends Value>(v: Vec<T>, p: (x: T) => boolean) => boolean;
export declare const every: <T extends Value>(v: Vec<T>, p: (x: T) => boolean) => boolean;
export declare const indexOf: <T extends Value>(v: Vec<T>, x: T) => number;
export declare const toArray: <T extends Value>(v: Vec<T>) => T[];
