/**
 * The workspace trireme generates for a job.
 *
 * Deterministic by construction: the manifest is the only input, nothing here
 * reads a clock, a path or the environment. The generated files are not
 * addressable by any tool, so the agent cannot rewrite the rules it works under.
 */
import { moduleImportSpecifier, moduleImportTarget } from "./layout.ts";
import type { Manifest } from "./types.ts";

export interface GeneratedFile {
  path: string;
  content: string;
}

export const GENERATED_PATHS: readonly string[] = [
  "package.json",
  "tsconfig.json",
  "tsconfig.build.json",
  "vitest.config.ts",
  "conformance.ts",
  "src/index.ts",
];

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

/**
 * The workspace's package.json. A pure function of the manifest and the set of
 * declared modules: the harness rewrites it whenever a module is declared or
 * deleted, which is how `#name` imports resolve without the agent ever knowing
 * where a module lives.
 */
export function workspacePackageJson(manifest: Manifest, modules: readonly string[]): string {
  const value: Record<string, unknown> = { name: manifest.name, version: manifest.version };
  if (manifest.description !== undefined) value["description"] = manifest.description;
  value["type"] = "module";
  // Tests run on source, so the package resolves to TypeScript. The artifact's
  // manifest is written by the packer and points at the build output instead.
  value["exports"] = { ".": "./src/index.ts" };
  if (modules.length > 0) {
    value["imports"] = Object.fromEntries(
      [...modules].sort().map((module) => [moduleImportSpecifier(module), moduleImportTarget(module)]),
    );
  }
  return json(value);
}

const TSCONFIG = json({
  compilerOptions: {
    target: "es2023",
    lib: ["es2023"],
    module: "nodenext",
    moduleResolution: "nodenext",
    types: ["node"],
    strict: true,
    noFallthroughCasesInSwitch: true,
    noEmit: true,
    skipLibCheck: true,
  },
  include: ["src", "acceptance", "contract.d.ts", "conformance.ts"],
});

const TSCONFIG_BUILD = json({
  extends: "./tsconfig.json",
  compilerOptions: {
    noEmit: false,
    declaration: true,
    outDir: "dist",
    rootDir: "src",
  },
  include: ["src"],
  exclude: ["src/**/*.test.ts"],
});

const VITEST_CONFIG = `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // The acceptance suite decides whether the package is finished; a module's
    // own tests are the agent's working instrument and are run separately.
    include: ["acceptance/**/*.test.ts", "src/modules/**/*.test.ts"],
    pool: "forks",
    testTimeout: 20000,
  },
});
`;

const CONFORMANCE = `/**
 * Generated by trireme. Asserts that the implementation and the contract are
 * mutually assignable: neither may drift from the other and still typecheck.
 */
import type * as Contract from "./contract.d.ts";
import type * as Implementation from "./src/index.ts";

const implementationMeetsContract: typeof Contract = null as unknown as typeof Implementation;
const contractCoversImplementation: typeof Implementation = null as unknown as typeof Contract;

void implementationMeetsContract;
void contractCoversImplementation;
`;

const ENTRY_PLACEHOLDER = `// Nothing is implemented yet.
//
// contract.d.ts fixes the shape of what belongs here, spec.md fixes what it
// must mean, and acceptance/ decides when it is finished.
export {};
`;

export function scaffoldWorkspace(manifest: Manifest): GeneratedFile[] {
  return [
    { path: "package.json", content: workspacePackageJson(manifest, []) },
    { path: "tsconfig.json", content: TSCONFIG },
    { path: "tsconfig.build.json", content: TSCONFIG_BUILD },
    { path: "vitest.config.ts", content: VITEST_CONFIG },
    { path: "conformance.ts", content: CONFORMANCE },
    { path: "src/index.ts", content: ENTRY_PLACEHOLDER },
  ];
}
